# Generated by Django 4.2.7 on 2024-10-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDS', '0003_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exposure',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
