# Generated by Django 4.2.7 on 2024-10-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDS', '0004_question_exposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dist',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='mode',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='state',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
